### ISSUE TITLE
power shell script issue with csv

### ISSUE THREAD

**Issue by sm-palo** [TheScriptGuy/PrismaAccess-EgressIPs#10]
oringnal code
".csv"  { 
    $csvOutput = foreach ($item in $resultData) {
        foreach ($detail in $item.address_details) {
            [PSCustomObject]@{
                Zone        = $item.zone
                ServiceType = $detail.serviceType
                Address     = $detail.address
                AddressType = $detail.addressType
            }
        }
    $csvOutput | Export-Csv -Path $outputFile -NoTypeInformation
    }
}

correct code 

".csv"  { 
    $csvOutput = foreach ($item in $resultData) {
        foreach ($detail in $item.address_details) {
            [PSCustomObject]@{
                Zone        = $item.zone
                ServiceType = $detail.serviceType
                Address     = $detail.address
                AddressType = $detail.addressType
            }
        }
    }
    $csvOutput | Export-Csv -Path $outputFile -NoTypeInformation
}

Moved the Export-Csv cmdlet outside the inner loop to ensure $csvOutput is correctly populated before attempting to export it.
Ensured proper initialization and handling of $csvOutput.
By making these changes, the script should now handle the output to CSV correctly and avoid the error related to null input objects.

**Comment by TheScriptGuy** [comment]
Thanks for pointing this out. I've fixed the code.
